title: Test Just the Docs Template
description: Test A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://rauf-dev.github.io/test-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
